import type { Metadata } from "next";
import { Nunito, Archivo_Black, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConditionalChrome from "@/components/shared/ConditionalChrome";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
const nunito = Nunito({ subsets: ["latin"], variable: "--font-nunito" });
const archivoBlack = Archivo_Black({ subsets: ["latin"], weight: "400", variable: "--font-archivo" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${nunito.variable} ${archivoBlack.variable}`}
    >
      <body suppressHydrationWarning className="font-sans antialiased">
        <ConditionalChrome>{children}</ConditionalChrome>
      </body>
    </html>
  );
} 